apiVersion: v1
kind: ConfigMap
metadata:
  name: voistra-server-config
  namespace: voistra
data:
  HOST: "0.0.0.0"
  PORT: "3000"
  CLIENT_URL: "https://voistra.example.com"
  DB_TYPE: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "diploma_voip"
  DB_SYNCHRONIZE: "false"
  DB_MIGRATIONS_RUN: "false"
  REDIS_URL: "redis://redis:6379"
  TURN_URL: "turn:turn.example.com:3478"
  TURN_REALM: "turn.example.com"
  TURN_USERNAME: "demo"
