import type { Language } from './types';

export const COPY = {
  ru: {
    appReady: 'Voistra готова к работе',
    authHeadline: 'Voistra',
    authBody: 'Быстрый вход в рабочее пространство.',
    login: 'Вход',
    register: 'Регистрация',
    username: 'Логин',
    displayName: 'Отображаемое имя',
    password: 'Пароль',
    createAccount: 'Создать аккаунт',
    signIn: 'Войти',
    logOut: 'Выйти',
    newServer: 'Новый сервер',
    ownerSpace: 'Пространство владельца',
    serverName: 'Название сервера',
    description: 'Описание',
    createServer: 'Создать сервер',
    joinServer: 'Войти на сервер',
    byId: 'По ID',
    joinByServerId: 'Подключиться по ID сервера',
    pasteServerId: 'Вставь ID сервера',
    noDescription: 'Без описания',
    members: 'участников',
    channels: 'каналов',
    manageAccess: 'Управление',
    memberAccess: 'Доступ участника',
    text: 'Текст',
    voice: 'Голос',
    privateChannel: 'Приватный канал',
    createChannel: 'Создать канал',
    ownerOnlyChannels: 'Создавать и удалять каналы может только владелец сервера.',
    privateState: 'Приватный',
    openState: 'Открыт',
    status: 'Статус',
    chooseChannel: 'Выбери канал',
    metricTicks: 'циклов метрик',
    textChat: 'Текстовый чат',
    messages: 'сообщений',
    typeMessage: 'Напиши сообщение',
    send: 'Отправить',
    serverOverview: 'Обзор сервера',
    owner: 'Владелец',
    yourRole: 'Твоя роль',
    ownerConsole: 'Консоль владельца',
    serverSettings: 'Настройки сервера',
    saveServer: 'Сохранить сервер',
    memberDirectory: 'Участники',
    people: 'чел.',
    remove: 'Удалить',
    voiceControl: 'Голос',
    voiceRoomLimit: 'До 10 участников',
    joinVoice: 'Войти в голос',
    leaveVoice: 'Выйти из голоса',
    mute: 'Микрофон',
    unmute: 'Включить микрофон',
    deafen: 'Звук',
    undeafen: 'Включить звук',
    speakingState: 'Говорю',
    pushToTalk: 'Push-to-talk',
    voiceActivation: 'Активация голосом',
    voiceSettings: 'Настройки голоса',
    captureSettings: 'Захват и звук',
    noiseSuppression: 'Шумоподавление',
    echoCancellation: 'Эхо-подавление',
    autoGainControl: 'Автоусиление',
    allowStreamAudio: 'Передавать системный звук',
    deleteChannel: 'Удалить канал',
    screenShare: 'Демонстрация экрана',
    inactive: 'Не активна',
    startShare: 'Начать',
    stopShare: 'Остановить',
    shareHint:
      'Каждый участник может публиковать один экран. В комнате на троих двое могут смотреть одного, либо все трое могут показывать экран одновременно.',
    liveShares: 'Активные трансляции',
    noShares: 'Пока никто не делится экраном. Запусти демонстрацию, чтобы опубликовать превью для всех в голосовой комнате.',
    connectionMetrics: 'Метрики соединения',
    realtimeUpdates: 'Обновления в реальном времени',
    webrtcDebug: 'Отладка WebRTC',
    noPeerDiagnostics: 'Пока нет данных о peer-соединениях',
    joinVoiceForDebug: 'Зайди в голосовой канал с другим клиентом, чтобы увидеть состояние signaling и ICE.',
    selectChannelBegin: 'Выбери канал',
    selectChannelHelp: 'Создай сервер или войди на существующий, затем открой текстовый или голосовой раздел внутри Voistra.',
    appLanguage: 'Язык',
    russian: 'Русский',
    english: 'English',
    lockedChannel: 'Этот канал защищён паролем',
    unlockChannel: 'Открыть канал',
    channelPassword: 'Пароль канала',
    cancel: 'Отмена',
    connect: 'Подключить',
    participantVolume: 'Громкость участника',
    shareVolume: 'Громкость трансляции',
    fullscreen: 'Во весь экран',
    speaking: 'Говорит',
    idle: 'Не говорит',
    micOpen: 'Микрофон открыт',
    mutedState: 'Микрофон выключен',
    listening: 'Слышит',
    deafenedState: 'Звук выключен',
    sharing: 'Трансляция',
    live: 'В эфире',
    you: 'Ты',
    remoteScreen: 'экран',
    yourSharePublished: 'Твоя трансляция отправляется всем peer-подключениям.',
    remoteSharePending: 'Удалённая трансляция появится ниже, как только видеотрек будет прикреплён.',
    channelPeers: 'Получателей в канале',
    browser: 'браузер',
    updateServerName: 'Обновить название сервера',
    updateDescription: 'Обновить описание',
    general: 'основной',
    unknownUser: 'Неизвестный пользователь',
    turnReady: 'TURN готов',
    realtimeConnected: 'Realtime подключён',
    realtimeDisconnected: 'Realtime отключён',
    connectedToVoice: 'Подключён к голосовому каналу',
    disconnectedFrom: 'Отключён от',
    joinedServer: 'Подключился к серверу',
    authenticatedAs: 'Выполнен вход как',
    serverUpdated: 'Сервер обновлён',
    serverMemberRemoved: 'Участник удалён',
    channelRemoved: 'Канал удалён',
    ownerRole: 'Владелец',
    adminRole: 'Администратор',
    memberRole: 'Участник',
    unknownOwner: 'Неизвестный владелец',
    serverId: 'Server ID',
    activeNow: 'активно',
    desktop: 'desktop',
    unknown: 'неизвестно',
    appVersion: 'Версия',
    serverDraftName: 'Команда Voistra',
    serverDraftDescription: 'Спокойное голосовое пространство для команды',
    textChannels: 'Текстовые каналы',
    voiceChannels: 'Голосовые каналы',
    voiceMembers: 'Участники голоса',
    peers: 'peers',
    rtt: 'RTT',
    jitter: 'Jitter',
    packetLoss: 'Потери',
    bitrate: 'Битрейт',
    lastEvent: 'Последнее событие',
    signaling: 'Сигналинг',
    ice: 'ICE',
    peer: 'Peer',
    localDescription: 'Локальное описание',
    remoteDescription: 'Удалённое описание',
    localTracks: 'Локальные треки',
    remoteTracks: 'Удалённые треки',
    offersAnswers: 'Offer/answer',
    iceSentReceived: 'ICE отправлено/получено',
    pendingIce: 'ICE в очереди',
    updated: 'Обновлено',
    audioTrack: 'аудио',
    videoTrack: 'видео',
    yes: 'да',
    no: 'нет',
    unexpectedError: 'Непредвиденная ошибка',
    serversTab: 'Серверы',
    friendsTab: 'Друзья',
    profileTab: 'Профиль',
    profileSettings: 'Профиль и настройки',
    profileSubtitle: 'Аватар, имя, пароль и голосовые параметры в одном месте.',
    avatarUrl: 'Ссылка на аватар',
    bio: 'О себе',
    saveProfile: 'Сохранить профиль',
    currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль',
    audioDefaults: 'Параметры аудио по умолчанию',
    audioMode: 'Режим обработки',
    voiceFocusMode: 'Voice Focus',
    balancedMode: 'Balanced',
    studioMode: 'Studio',
    voiceFocusHint: 'Максимально очищает голос для созвонов и шумных комнат.',
    balancedHint: 'Сохраняет баланс между чистотой речи и естественностью.',
    studioHint: 'Минимум обработки для хорошего микрофона и тихой комнаты.',
    findPeople: 'Найти пользователей',
    searchUsers: 'Поиск по имени или ID',
    addFriend: 'Добавить в друзья',
    friendRequests: 'Заявки',
    incoming: 'Входящие',
    outgoing: 'Исходящие',
    accept: 'Принять',
    removeFriend: 'Удалить из друзей',
    directMessages: 'Личные сообщения',
    openDialog: 'Открыть диалог',
    startDialog: 'Начать диалог',
    noFriends: 'Пока нет друзей. Найди пользователя и отправь заявку.',
    noConversations: 'Пока нет личных сообщений.',
    dmPlaceholder: 'Напиши личное сообщение',
    copyId: 'Скопировать ID',
    copyServer: 'Поделиться сервером',
    copied: 'Скопировано',
    testVoice: 'Проверка голоса',
    voiceTestHint: 'Скажи что-нибудь, чтобы увидеть, что микрофон активен.',
    micLevel: 'Уровень микрофона',
    outputDevice: 'Вывод звука',
    defaultOutput: 'Системный вывод',
    hubSubtitle: 'Серверы, лички, друзья и голосовые настройки в одном desktop-клиенте.',
    linkedTextRoom: 'Связанный текстовый чат',
    overviewTab: 'Обзор',
    membersTab: 'Участники',
    settingsTab: 'Настройки',
    requestsTab: 'Заявки',
    dialogsTab: 'Диалоги',
    profileIdentity: 'Твоя учётная запись',
    ownerQuickActions: 'Быстрые действия владельца',
    socialSearchResults: 'Результаты поиска',
    friendSince: 'В друзьях с',
    accountTab: 'Аккаунт',
    securityTab: 'Безопасность',
    audioTab: 'Аудио',
    chooseImage: 'Выбрать фото',
    removeImage: 'Убрать фото',
    online: 'В сети',
    offline: 'Не в сети',
    inputLevel: 'Чувствительность микрофона',
    outputLevel: 'Громкость вывода',
    reconnectLabel: 'Автоподключение',
  },
  en: {
    appReady: 'Voistra workspace ready',
    authHeadline: 'Voistra',
    authBody: 'A focused desktop voice workspace.',
    login: 'Login',
    register: 'Register',
    username: 'Username',
    displayName: 'Display name',
    password: 'Password',
    createAccount: 'Create account',
    signIn: 'Sign in',
    logOut: 'Log out',
    newServer: 'New server',
    ownerSpace: 'Owner space',
    serverName: 'Server name',
    description: 'Description',
    createServer: 'Create server',
    joinServer: 'Join server',
    byId: 'By ID',
    joinByServerId: 'Join by server ID',
    pasteServerId: 'Paste server ID',
    noDescription: 'No description',
    members: 'members',
    channels: 'channels',
    manageAccess: 'Manage access',
    memberAccess: 'Member access',
    text: 'Text',
    voice: 'Voice',
    privateChannel: 'Private channel',
    createChannel: 'Create channel',
    ownerOnlyChannels: 'Only the server owner can create or remove channels.',
    privateState: 'Private',
    openState: 'Open',
    status: 'Status',
    chooseChannel: 'Choose channel',
    metricTicks: 'metric ticks',
    textChat: 'Text chat',
    messages: 'messages',
    typeMessage: 'Type a message',
    send: 'Send',
    serverOverview: 'Server overview',
    owner: 'Owner',
    yourRole: 'Your role',
    ownerConsole: 'Owner console',
    serverSettings: 'Server settings',
    saveServer: 'Save server',
    memberDirectory: 'Member directory',
    people: 'people',
    remove: 'Remove',
    voiceControl: 'Voice',
    voiceRoomLimit: 'Up to 10 participants',
    joinVoice: 'Join voice',
    leaveVoice: 'Leave voice',
    mute: 'Mute mic',
    unmute: 'Unmute mic',
    deafen: 'Mute output',
    undeafen: 'Unmute output',
    speakingState: 'Speaking',
    pushToTalk: 'Push-to-talk',
    voiceActivation: 'Voice activation',
    voiceSettings: 'Voice settings',
    captureSettings: 'Capture and audio',
    noiseSuppression: 'Noise suppression',
    echoCancellation: 'Echo cancellation',
    autoGainControl: 'Auto gain',
    allowStreamAudio: 'Share system audio',
    deleteChannel: 'Delete channel',
    screenShare: 'Screen share',
    inactive: 'Inactive',
    startShare: 'Start',
    stopShare: 'Stop',
    shareHint:
      'Every participant can publish one live screen. In a three-person room, two people can watch one sharer, or all three can share at the same time.',
    liveShares: 'Live shares',
    noShares: 'No one is sharing yet. Start a share to publish a preview to everyone in this voice room.',
    connectionMetrics: 'Connection metrics',
    realtimeUpdates: 'Realtime updates',
    webrtcDebug: 'WebRTC debug',
    noPeerDiagnostics: 'No peer diagnostics yet',
    joinVoiceForDebug: 'Join a voice channel with another client to populate signaling and ICE state.',
    selectChannelBegin: 'Select a channel',
    selectChannelHelp: 'Create or join a server, then open a text or voice space inside Voistra.',
    appLanguage: 'Language',
    russian: 'Russian',
    english: 'English',
    lockedChannel: 'This channel is password protected',
    unlockChannel: 'Unlock channel',
    channelPassword: 'Channel password',
    cancel: 'Cancel',
    connect: 'Connect',
    participantVolume: 'Participant volume',
    shareVolume: 'Share volume',
    fullscreen: 'Fullscreen',
    speaking: 'Speaking',
    idle: 'Idle',
    micOpen: 'Mic open',
    mutedState: 'Muted',
    listening: 'Listening',
    deafenedState: 'Deafened',
    sharing: 'Sharing',
    live: 'Live',
    you: 'You',
    remoteScreen: 'screen',
    yourSharePublished: 'Your share is being published to every peer connection.',
    remoteSharePending: 'Remote share will appear below as soon as the video track is attached.',
    channelPeers: 'Channel peers',
    browser: 'browser',
    updateServerName: 'Update server name',
    updateDescription: 'Update description',
    general: 'general',
    unknownUser: 'Unknown user',
    turnReady: 'TURN ready',
    realtimeConnected: 'Realtime connected',
    realtimeDisconnected: 'Realtime disconnected',
    connectedToVoice: 'Connected to voice channel',
    disconnectedFrom: 'Disconnected from',
    joinedServer: 'Joined server',
    authenticatedAs: 'Authenticated as',
    serverUpdated: 'Server updated',
    serverMemberRemoved: 'Server member removed',
    channelRemoved: 'Channel removed',
    ownerRole: 'Owner',
    adminRole: 'Admin',
    memberRole: 'Member',
    unknownOwner: 'Unknown owner',
    serverId: 'Server ID',
    activeNow: 'active',
    desktop: 'desktop',
    unknown: 'unknown',
    appVersion: 'App',
    serverDraftName: 'Voistra Team',
    serverDraftDescription: 'Calm voice workspace',
    textChannels: 'Text channels',
    voiceChannels: 'Voice channels',
    voiceMembers: 'Voice members',
    peers: 'peers',
    rtt: 'RTT',
    jitter: 'Jitter',
    packetLoss: 'Packet loss',
    bitrate: 'Bitrate',
    lastEvent: 'Last event',
    signaling: 'Signaling',
    ice: 'ICE',
    peer: 'Peer',
    localDescription: 'Local description',
    remoteDescription: 'Remote description',
    localTracks: 'Local tracks',
    remoteTracks: 'Remote tracks',
    offersAnswers: 'Offers/answers',
    iceSentReceived: 'ICE sent/received',
    pendingIce: 'Pending ICE',
    updated: 'Updated',
    audioTrack: 'audio',
    videoTrack: 'video',
    yes: 'yes',
    no: 'no',
    unexpectedError: 'Unexpected error',
    serversTab: 'Servers',
    friendsTab: 'Friends',
    profileTab: 'Profile',
    profileSettings: 'Profile and settings',
    profileSubtitle: 'Avatar, identity, password and voice defaults in one place.',
    avatarUrl: 'Avatar URL',
    bio: 'Bio',
    saveProfile: 'Save profile',
    currentPassword: 'Current password',
    newPassword: 'New password',
    audioDefaults: 'Default audio settings',
    audioMode: 'Processing mode',
    voiceFocusMode: 'Voice Focus',
    balancedMode: 'Balanced',
    studioMode: 'Studio',
    voiceFocusHint: 'Stronger cleanup for calls and noisy rooms.',
    balancedHint: 'A balanced voice chain for everyday conversations.',
    studioHint: 'Minimal processing for a good microphone in a quiet room.',
    findPeople: 'Find people',
    searchUsers: 'Search by name or ID',
    addFriend: 'Add friend',
    friendRequests: 'Requests',
    incoming: 'Incoming',
    outgoing: 'Outgoing',
    accept: 'Accept',
    removeFriend: 'Remove friend',
    directMessages: 'Direct messages',
    openDialog: 'Open dialog',
    startDialog: 'Start dialog',
    noFriends: 'No friends yet. Search for a user and send a request.',
    noConversations: 'No direct messages yet.',
    dmPlaceholder: 'Write a direct message',
    copyId: 'Copy ID',
    copyServer: 'Share server',
    copied: 'Copied',
    testVoice: 'Voice check',
    voiceTestHint: 'Say something to confirm your microphone is active.',
    micLevel: 'Microphone level',
    outputDevice: 'Audio output',
    defaultOutput: 'System output',
    hubSubtitle: 'Servers, DMs, friends and voice controls in one desktop client.',
    linkedTextRoom: 'Linked text chat',
    overviewTab: 'Overview',
    membersTab: 'Members',
    settingsTab: 'Settings',
    requestsTab: 'Requests',
    dialogsTab: 'Dialogs',
    profileIdentity: 'Your account',
    ownerQuickActions: 'Owner quick actions',
    socialSearchResults: 'Search results',
    friendSince: 'Friends since',
    accountTab: 'Account',
    securityTab: 'Security',
    audioTab: 'Audio',
    chooseImage: 'Choose image',
    removeImage: 'Remove image',
    online: 'Online',
    offline: 'Offline',
    inputLevel: 'Mic sensitivity',
    outputLevel: 'Output volume',
    reconnectLabel: 'Reconnect',
  },
} as const;

export type AppCopy = (typeof COPY)[Language];
